engines:
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
    
ratings:
    paths:
    - "**.php"

exclude_paths:
- envs/**/*
- tests/**/*
- sql/**/*
- scripts/**/*
- docs/**/*
- vendor/**/*
