engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  gofmt:
    enabled: true
  eslint:
    enabled: true
    checks:
      no-trailing-spaces:
        enabled: false
  csslint:
    enabled: false

ratings:
    paths:
    - src/**
    - modules/**

exclude_paths:
- "envs/kickstarter/resources/**/*"
- "envs/dev/resources/**/*"
- "tests/**/*"
- "sql/**/*"
- "scripts/**/*"
- "docs/**/*"
