engines:
  phpmd:
    enabled: true
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
    
ratings:
    paths:
    - src/**
    - modules/**

exclude_paths:
- "envs/**/*"
- "tests/**/*"
- "sql/**/*"
- "scripts/**/*"
- "docs/**/*"
- "vendor/**/*"
