engines:
  phpcodesniffer:
    enabled: true
  rubocop:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false

ratings:
    paths:
    - src/**
    - modules/**

exclude_paths:
- "envs/kickstarter/resources/**/*"
- "envs/dev/resources/**/*"
- "tests/**/*"
- "sql/**/*"
- "scripts/**/*"
- "docs/**/*"
