engines:
  phpcodesniffer:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false

ratings:
    paths:
    - "**.php"

exclude_paths:
- "envs/**/*"
- "tests/**/*"
- "sql/**/*"
- "scripts/**/*"
- "docs/**/*"
