language: php

php:
  - 5.5
  - 5.6
  - 7
  
sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql -e 'create database myapp_test;'  
  - mysql -u root myapp_test < tests/sql/1.0.0-beta1.sql
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"
    fi

script:
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --configuration travis.phpunit.xml
  
after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      vendor/bin/test-reporter
    fi
